# Generated by Django 5.2.7 on 2025-11-02 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE')),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
                'db_table': 'ai_provider',
                'indexes': [models.Index(fields=['name', 'status'], name='ai_provider_name_status')],
            },
        ),
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automator.aiprovider')),
            ],
            options={
                'verbose_name': 'Ai Model',
                'verbose_name_plural': 'Ai Models',
                'db_table': 'ai_model',
                'indexes': [models.Index(fields=['name'], name='ai_model_name')],
            },
        ),
    ]
